name: CI, CD, Front End Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev ffmpeg
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
          pipenv install python-dotenv
          pipenv install pytest-cov

      - name: Run tests with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/tests
        run: |
          pipenv run pytest tests/
          pipenv run python -m coverage run -m pytest tests/
          pipenv run python -m coverage report

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Web-App Docker Image
        run: |
          docker build -f web_app/Dockerfile -t capks/web_app:latest ./web_app
          docker push capks/web_app:latest

      - name: Build and Push ML Client Docker Image
        run: |
          docker build -f machine-learning-client/Dockerfile -t capks/machine-learning-client:latest ./machine-learning-client
          docker push capks/machine-learning-client:latest

      - name: Build and Push MongoDB Docker Image
        run: |
          docker build -f mongodb/Dockerfile -t capks/mongodb:latest ./mongodb
          docker push capks/mongodb:latest

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIGITALOCEAN_DROPLET_IP }} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkNAf9n63w3dXq3fNc2GMkzUaWYToiIi4/okNE5atUo" >> ~/.ssh/known_hosts

      - name: List files in the GitHub Actions workspace
        run: ls -alh $GITHUB_WORKSPACE
        
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /var/www/myapp
            docker-compose pull
            docker-compose down
            docker-compose up -d

